---
name: Pod-Strip
version: 1.02
author:
  - 'Thomas Klausner <domm@zsi.at>'
abstract: Remove POD from Perl code
license: perl
requires:
  Pod::Simple: 3.00
  Test::More: 0
provides:
  Pod::Strip:
    file: lib/Pod/Strip.pm
    version: 1.02
generated_by: Module::Build version 0.2611
